fos_user_security:

    resource: "@FOSUserBundle/Resources/config/routing/security.xml"


fos_user_profile:

    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"

    prefix: /profile


fos_user_resetting:

    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"

    prefix: /resetting


fos_user_change_password:

    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"

    prefix: /profile


compte:
    resource: "@compteBundle/Resources/config/routing.yml"
    prefix:   /

c_user:
    resource: "@CUserBundle/Resources/config/routing.yml"
    prefix:   /

