# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        CUserBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_SUPER_ADMIN: [ROLE_SUPERVISOR,ROLE_APPROVER,ROLE_OPERATOR,ROLE_USER,ROLE_ALLOWED_TO_SWITCH]


    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        main:
            entity:    
                class:    CUserBundle\Entity\User    
                property: username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:        ^/

            anonymous:      true

            provider:       main

            form_login:

                login_path: fos_user_security_login

                check_path: fos_user_security_check

            logout:

                path:       fos_user_security_logout

                target:     /login

            remember_me:

                key:        %secret%

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/users, roles: ROLE_SUPER_ADMIN }
        - { path: ^/, roles: ROLE_USER }