# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    app.form.registration:
        class: CUserBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: cuser_user_registration }

    app.form.profile:
        class: CUserBundle\Form\ProfileType
        tags:
            - { name: form.type, alias: cuser_user_profile}

    movement.type.form:
            class: compteBundle\Form\MovementType
            arguments:
                - '@security.token_storage'
            tags:
                - { name: form.type }

    gestionCompte.notifications.html:
        class: compteBundle\Notifications\NotificationsHTML

    gestionCompte.n2l.html:
        class: compteBundle\N2L\NumToAr

    gestionCompte.notifications.listener:
        class: compteBundle\Notifications\NotificationsListener
        arguments: ["@gestionCompte.notifications.html", "@doctrine.orm.entity_manager","@security.token_storage"]
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: processNotif }