users:
    path:     /
    defaults: { _controller: "CUserBundle:Users:index" }

users_show:
    path:     /{username}/show
    defaults: { _controller: "CUserBundle:Users:show" }

users_new:
    path:     /new
    defaults: { _controller: "CUserBundle:Users:new" }

users_create:
    path:     /create
    defaults: { _controller: "CUserBundle:Users:create" }
    methods:  POST

users_edit:
    path:     /{username}/edit
    defaults: { _controller: "CUserBundle:Users:edit" }

users_update:
    path:     /{username}/update
    defaults: { _controller: "CUserBundle:Users:update" }
    methods:  [POST, PUT]

users_manage:
    path:     /{username}/manage
    defaults: { _controller: "CUserBundle:Users:manage" }
    methods:  [POST, DELETE]
    
users_delete:
    path:     /{username}/delete
    defaults: { _controller: "CUserBundle:Users:delete" }
    methods:  [POST, DELETE]
    