account_index:
    path:     /
    defaults: { _controller: "compteBundle:Account:index" }
    methods:  GET

account_show:
    path:     /{id}/show
    defaults: { _controller: "compteBundle:Account:show" }
    methods:  GET

account_releve:
    path:     /{id}/releve
    defaults: { _controller: "compteBundle:Account:releve" }
    methods:  GET

account_new:
    path:     /new
    defaults: { _controller: "compteBundle:Account:new" }
    methods:  [GET, POST]

account_edit:
    path:     /{id}/edit
    defaults: { _controller: "compteBundle:Account:edit" }
    methods:  [GET, POST]

account_delete:
    path:     /{id}/delete
    defaults: { _controller: "compteBundle:Account:delete" }
    methods:  DELETE
