delegation_index:
    path:     /
    defaults: { _controller: "compteBundle:Delegation:index" }
    methods:  GET

delegation_show:
    path:     /{id}/show
    defaults: { _controller: "compteBundle:Delegation:show" }
    methods:  GET

delegation_new:
    path:     /new
    defaults: { _controller: "compteBundle:Delegation:new" }
    methods:  [GET, POST]

delegation_edit:
    path:     /{id}/edit
    defaults: { _controller: "compteBundle:Delegation:edit" }
    methods:  [GET, POST]

delegation_delete:
    path:     /{id}/delete
    defaults: { _controller: "compteBundle:Delegation:delete" }
    methods:  DELETE
