morass_index:
    path:     /
    defaults: { _controller: "compteBundle:Morass:index" }
    methods:  GET

morass_show:
    path:     /{id}/show
    defaults: { _controller: "compteBundle:Morass:show" }
    methods:  GET

morass_new:
    path:     /new
    defaults: { _controller: "compteBundle:Morass:new" }
    methods:  [GET, POST]

morass_edit:
    path:     /{id}/edit
    defaults: { _controller: "compteBundle:Morass:edit" }
    methods:  [GET, POST]

morass_delete:
    path:     /{id}/delete
    defaults: { _controller: "compteBundle:Morass:delete" }
    methods:  DELETE

morass_morass:
    path:      /{id}/morass
    defaults: { _controller: "compteBundle:Morass:morass" }
    methods:  GET