movement_index:
    path:     /
    defaults: { _controller: "compteBundle:Movement:index" }
    methods:  GET

movement_show:
    path:     /{id}/show
    defaults: { _controller: "compteBundle:Movement:show" }
    methods:  GET

movement_new:
    path:     /new
    defaults: { _controller: "compteBundle:Movement:new" }
    methods:  [GET, POST]

movement_edit:
    path:     /{id}/edit
    defaults: { _controller: "compteBundle:Movement:edit" }
    methods:  [GET, POST]

movement_delete:
    path:     /{id}/delete
    defaults: { _controller: "compteBundle:Movement:delete" }
    methods:  DELETE

movement_approve:
    path:     /{id}/process_movement
    defaults: { _controller: "compteBundle:Movement:processMovement" }
    methods:  POST
