<?php

namespace compteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AccountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccountRepository extends EntityRepository
{
	public function getAccountProperty(){

		$qb = $this->createQueryBuilder('a');


			  $qb->where('a.account IS NULL')

			  ;
			  return $qb;
	}
}
