<?php

namespace compteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DelegationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DelegationRepository extends EntityRepository
{
}
