<?php

namespace compteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ExpenseTransferRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExpenseTransferRepository extends EntityRepository
{
}
