<?php

namespace compteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ExternalAccountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExternalAccountRepository extends EntityRepository
{
}
