<?php

namespace compteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MasterEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MasterEntityRepository extends EntityRepository
{
}
