<?php

namespace compteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MorassRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MorassRepository extends EntityRepository
{
}
