<?php

namespace CUserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{

	public function getMasterEntitySupervisor($masterEntity){

		$qb = $this->createQueryBuilder('u');
			  $qb->where('u.roles like :role')
			  	->setParameter('role', 'ROLE_SUPERVISOR')
			  	->andWhere('u.masterEntity= :masterEntity')
			  	->setParameter('masterEntity', $masterEntity)
			  	->setMaxResults(1);
			  return $qb;
	}
}
